name: RankPlugin
version: 1.0.1
main: ir.slapland.rankplugin.RankPlugin
api-version: '1.20'
author: Slap Land
softdepend: [LuckPerms]
commands:
  rank:
    description: Change a player's rank through LuckPerms
    usage: /rank <Player_Name> the <Rank_Name>
    permission: rankplugin.rank
    permission-message: "§cYou don't have permission to use this command."
permissions:
  rankplugin.rank:
    description: Allows using /rank
    default: false
