name: RankPlugin
version: 1.0.2
main: com.slapland.rankplugin.RankPlugin
api-version: '1.20'
author: Slap-Land
commands:
  rank:
    description: Change a player's LuckPerms rank
    usage: /rank <Player_Name> the <Rank_Name>
    permission: rankplugin.use
permissions:
  rankplugin.use:
    default: true
  rankplugin.admin:
    default: false
  rankplugin.owner:
    default: false
